language: ruby
rvm:
- 2.4
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - DEPLOY_KEY_PATH=_deploy/keys/prod_rsa
branches:
  only:
  - master
sudo: false
script:
  - bundle exec jekyll build
  #- bundle exec rake test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0380117d5827_key -iv $encrypted_0380117d5827_iv
    -in "$DEPLOY_KEY_PATH".enc -out "$DEPLOY_KEY_PATH" -d
  - chmod 600 "$DEPLOY_KEY_PATH"
  - eval "$(ssh-agent -s)"
  - ssh-add "$DEPLOY_KEY_PATH"
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/*
    $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
